flags: {}
packages:
- '.'
extra-deps:
- loop-0.3.0
- matrix-0.3.5.0
- normaldistribution-1.1.0.3
- primitive-0.6.1.0
- random-1.1
- vector-0.11.0.0
install-ghc: true
resolver: ghc-7.10
skip-ghc-check: true
